using UnityEngine;

namespace ProjectPang
{
	public static class GlobalValue
	{
		// Probability
		public static readonly int ProbabilityMaxCount = 100; // 확률 계산 기준 정수

		// AutoGenerated File Path
		public static readonly string SOpath = "Assets/Resources/SO/AutoGenerated";
		public static readonly string ScriptPath = "Assets/Scripts/AutoGenerated";
	}
}
