using System;
using System.Collections.Generic;
using UnityEngine;

#if UNITY_EDITOR
using System.Collections;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using GoogleSheetsToUnity;
using GoogleSheetsToUnity.ThirdPary;
using UnityEditor;
using UnityEngine.Networking;
using UnityEngine.UIElements;
using UnityEditor.UIElements;
#endif

/// <summary>Editor import settings. Generated data and catalogs have no dependency on this tool.</summary>
[CreateAssetMenu(menuName = "Data/Google Spreadsheet Reader", fileName = "GoogleSpeadSheetReader")]
public sealed class GoogleSpeadSheetReader : ScriptableObject
{
    public enum AccessMode { Public, Private }
    public string spreadsheetId;
    public AccessMode accessMode;
    public string generatedCodeFolder = "Assets/01_Scripts/Data/Generated";
    public string dataFolder = "Assets/04_Data";
    public string catalogFolder = "Assets/04_Data/Catalogs";
    [Min(1)] public int requestTimeoutSeconds = 30;

    [Serializable]
    public sealed class Worksheet
    {
        public string title;
        public int sheetId;
        public int rowCount;
        public int columnCount;
    }

    [Serializable]
    public sealed class ManagedRow
    {
        public int key;
        public string guid;
    }

    // Ownership is source-, worksheet- and output-location-specific. Never scan a folder to delete assets.
    [Serializable]
    public sealed class ImportRecord
    {
        public string sourceId;
        public int sheetId;
        public string dataPath;
        public string catalogPath;
        public ScriptableObject catalog;
        public List<ManagedRow> rows = new List<ManagedRow>();
    }

    [SerializeField, HideInInspector] private List<Worksheet> worksheets = new List<Worksheet>();
    [SerializeField, HideInInspector] private List<ImportRecord> imports = new List<ImportRecord>();
    public IReadOnlyList<Worksheet> Worksheets => worksheets;
    public IReadOnlyList<ImportRecord> Imports => imports;

#if UNITY_EDITOR
    [NonSerialized] public bool IsBusy;
    [NonSerialized] public string Status = "시트 검색 또는 전체 검증으로 시작하세요.";
    [NonSerialized] public string LastError;
    internal List<Worksheet> MutableWorksheets => worksheets;
    internal List<ImportRecord> MutableImports => imports;
#endif
}

#if UNITY_EDITOR
/// <summary>All importer/editor implementation deliberately lives in this one source file.</summary>
public static class GoogleSpeadSheetReaderPipeline
{
    public const string GeneratedNamespace = "ProjectPang.GeneratedSheets";
    private const string Marker = "// Generated by GoogleSpeadSheetReader: ";
    private static readonly CultureInfo Invariant = CultureInfo.InvariantCulture;
    private static readonly Regex Identifier = new Regex(@"^[\p{L}_][\p{L}\p{Nd}_]*$", RegexOptions.CultureInvariant);
    private static readonly HashSet<string> Keywords = new HashSet<string>((
        "abstract as base bool break byte case catch char checked class const continue decimal default delegate " +
        "do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int " +
        "interface internal is lock long namespace new null object operator out override params private protected " +
        "public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw " +
        "true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while").Split(' '));
    private static readonly Dictionary<string, Type> ScalarTypes = new Dictionary<string, Type>
    {
        { "string", typeof(string) }, { "bool", typeof(bool) }, { "int", typeof(int) },
        { "long", typeof(long) }, { "float", typeof(float) }, { "double", typeof(double) }
    };

    public enum Operation { Discover, Validate, Generate, Import }

    public sealed class Column
    {
        public string name;
        public Type type;
        public int index;
    }

    public sealed class Row
    {
        public int key;
        public string name;
        public Dictionary<string, object> values = new Dictionary<string, object>();
    }

    public sealed class ParsedSheet
    {
        public GoogleSpeadSheetReader.Worksheet worksheet;
        public List<Column> columns = new List<Column>();
        public List<Row> rows = new List<Row>();
        public string signature;
        public string DataTypeName => worksheet.title + "Data";
        public string CatalogTypeName => worksheet.title + "Catalog";
    }

    [Serializable] private sealed class Metadata { public MetadataSheet[] sheets = null; }
    [Serializable] private sealed class MetadataSheet { public SheetProperties properties = null; }
    [Serializable] private sealed class SheetProperties
    {
        public string title = null;
        public int sheetId = 0;
        public string sheetType = null;
        public GridProperties gridProperties = null;
    }
    [Serializable] private sealed class GridProperties { public int rowCount = 0; public int columnCount = 0; }

    public static void Start(GoogleSpeadSheetReader reader, Operation operation)
    {
        if (reader.IsBusy) return;
        if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling || EditorUtility.scriptCompilationFailed)
        {
            reader.LastError = "Play Mode를 종료하고 모든 컴파일 오류를 해결한 후 실행하세요.";
            return;
        }
        // Serialize pending Inspector settings before the asynchronous operation/code recompile.
        EditorUtility.SetDirty(reader);
        AssetDatabase.SaveAssetIfDirty(reader);
        reader.IsBusy = true;
        reader.LastError = null;
        EditorCoroutineRunner.StartCoroutine(Guard(reader, Run(reader, operation)));
    }

    private static IEnumerator Guard(GoogleSpeadSheetReader reader, IEnumerator routine)
    {
        try
        {
            while (true)
            {
                object current;
                try
                {
                    if (!routine.MoveNext()) break;
                    current = routine.Current;
                }
                catch (Exception exception)
                {
                    reader.LastError = exception.Message;
                    reader.Status = "실패 — 가져오기 중단";
                    break;
                }
                yield return current;
            }
        }
        finally
        {
            (routine as IDisposable)?.Dispose();
            if (reader != null) reader.IsBusy = false;
        }
    }

    private static IEnumerator Run(GoogleSpeadSheetReader reader, Operation operation)
    {
        string sourceId = (reader.spreadsheetId ?? "").Trim();
        if (!Regex.IsMatch(sourceId, @"^[a-zA-Z0-9_-]+$"))
            throw new InvalidOperationException("유효한 Spreadsheet ID를 입력하세요. URL 전체가 아닌 ID가 필요합니다.");
        ValidateSettings(reader);
        var config = SpreadsheetManager.Config;
        if (config == null) throw new InvalidOperationException("GSTU_Config가 없습니다. 기존 GSTU 설정을 준비하세요.");
        var mode = reader.accessMode;
        int timeout = Math.Max(1, reader.requestTimeoutSeconds);
        if (mode == GoogleSpeadSheetReader.AccessMode.Public && string.IsNullOrWhiteSpace(config.API_Key))
            throw new InvalidOperationException("GSTU 설정의 API Key가 비어 있습니다.");
        if (mode == GoogleSpeadSheetReader.AccessMode.Private)
        {
            if (config.gdr == null || string.IsNullOrWhiteSpace(config.gdr.access_token))
                throw new InvalidOperationException("GSTU에서 비공개 Google Sheets 인증을 먼저 완료하세요.");
            reader.Status = "GSTU 인증 확인 중...";
            bool refreshed = false;
            Exception refreshError = null;
            EditorCoroutineRunner.StartCoroutine(RefreshToken(() => refreshed = true, e => refreshError = e));
            double until = EditorApplication.timeSinceStartup + timeout;
            while (!refreshed && refreshError == null && EditorApplication.timeSinceStartup < until) yield return null;
            if (refreshError != null) throw new InvalidOperationException("GSTU 인증 갱신에 실패했습니다.");
            if (!refreshed) throw new TimeoutException("GSTU 인증 갱신 시간이 초과되었습니다.");
            if (string.IsNullOrWhiteSpace(config.gdr.access_token) || config.gdr.nextRefreshTime <= DateTime.Now)
                throw new InvalidOperationException("GSTU 토큰이 유효하지 않습니다. 다시 인증하세요.");
        }

        reader.Status = "전체 worksheet 검색 중...";
        string url = "https://sheets.googleapis.com/v4/spreadsheets/" + sourceId +
            "?fields=sheets(properties(sheetId,title,sheetType,gridProperties(rowCount,columnCount)))";
        if (mode == GoogleSpeadSheetReader.AccessMode.Public) url += "&key=" + Uri.EscapeDataString(config.API_Key);
        List<GoogleSpeadSheetReader.Worksheet> discovered;
        using (var request = UnityWebRequest.Get(url))
        {
            request.timeout = timeout;
            if (mode == GoogleSpeadSheetReader.AccessMode.Private)
                request.SetRequestHeader("Authorization", "Bearer " + config.gdr.access_token);
            var pending = request.SendWebRequest();
            while (!pending.isDone) yield return null;
            if (request.result != UnityWebRequest.Result.Success)
                throw new InvalidOperationException("시트 검색 실패 (HTTP " + request.responseCode + "). 인증·접근 권한·연결을 확인하세요.");
            var metadata = JsonUtility.FromJson<Metadata>(request.downloadHandler.text);
            if (metadata?.sheets == null || metadata.sheets.Length == 0)
                throw new InvalidOperationException("조회된 worksheet가 없습니다.");
            discovered = new List<GoogleSpeadSheetReader.Worksheet>();
            foreach (var sheet in metadata.sheets)
            {
                var p = sheet.properties;
                if (p == null || p.gridProperties == null || p.sheetType != "GRID")
                    throw new InvalidOperationException("지원하지 않는 worksheet 형식: " + (p?.title ?? "unknown"));
                discovered.Add(new GoogleSpeadSheetReader.Worksheet
                { title = p.title, sheetId = p.sheetId, rowCount = p.gridProperties.rowCount, columnCount = p.gridProperties.columnCount });
            }
        }
        reader.MutableWorksheets.Clear();
        reader.MutableWorksheets.AddRange(discovered);
        EditorUtility.SetDirty(reader);
        if (operation == Operation.Discover)
        {
            AssetDatabase.SaveAssetIfDirty(reader);
            reader.Status = discovered.Count + "개 worksheet 검색 완료";
            yield break;
        }

        var sheets = new List<ParsedSheet>();
        foreach (var worksheet in discovered)
        {
            reader.Status = worksheet.title + " 다운로드 및 검증 중...";
            GstuSpreadSheet response = null;
            bool accepting = true;
            bool gstuFailed = false;
            // GSTU's public/private APIs do not expose an error callback. Its exceptions are logged by its runner.
            Application.LogCallback logHandler = (message, stack, kind) =>
            {
                if ((kind == LogType.Exception || kind == LogType.Error) && stack.Contains("GoogleSheetsToUnity"))
                    gstuFailed = true;
            };
            Application.logMessageReceived += logHandler;
            try
            {
                string quotedTitle = "'" + worksheet.title.Replace("'", "''") + "'";
                var search = new GSTU_Search(sourceId, quotedTitle, "A1",
                    ColumnLetters(worksheet.columnCount) + worksheet.rowCount, "A", 1);
                if (mode == GoogleSpeadSheetReader.AccessMode.Public)
                    SpreadsheetManager.ReadPublicSpreadsheet(search, data => { if (accepting) response = data; });
                else
                    SpreadsheetManager.Read(search, data => { if (accepting) response = data; });
                double until = EditorApplication.timeSinceStartup + timeout;
                while (response == null && !gstuFailed && EditorApplication.timeSinceStartup < until) yield return null;
                if (gstuFailed) throw new InvalidOperationException(worksheet.title + ": GSTU 요청 또는 응답 처리 실패. 데이터 자산을 변경하지 않았습니다.");
                if (response == null) throw new TimeoutException(worksheet.title + ": GSTU 응답 시간이 초과되었습니다. 데이터 자산을 변경하지 않았습니다.");
                sheets.Add(ParseSheet(worksheet, response));
            }
            finally
            {
                accepting = false;
                Application.logMessageReceived -= logHandler;
            }
        }
        ValidateTypeNames(sheets);
        if (reader.spreadsheetId.Trim() != sourceId || reader.accessMode != mode)
            throw new InvalidOperationException("실행 중 설정이 변경되었습니다. 다시 실행하세요.");

        if (operation == Operation.Generate)
        {
            GenerateCode(reader, sheets);
            reader.Status = "코드 생성 완료. 컴파일 완료 후 전체 데이터 가져오기를 실행하세요.";
        }
        else if (operation == Operation.Import)
        {
            ValidateCompiledSchema(reader, sheets);
            ApplyImport(reader, sourceId, sheets);
            reader.Status = sheets.Count + "개 시트 / " + sheets.Sum(s => s.rows.Count) + "개 행 가져오기 완료";
        }
        else
        {
            reader.Status = sheets.Count + "개 시트 / " + sheets.Sum(s => s.rows.Count) + "개 행 데이터 검증 성공";
            try { ValidateCompiledSchema(reader, sheets); }
            catch (InvalidOperationException e) { reader.Status += "\n" + e.Message; }
        }
    }

    private static IEnumerator RefreshToken(Action success, Action<Exception> failure)
    {
        var routine = GoogleAuthrisationHelper.CheckForRefreshOfToken();
        while (true)
        {
            object current;
            try
            {
                if (!routine.MoveNext()) { success(); yield break; }
                current = routine.Current;
            }
            catch (Exception e) { failure(e); yield break; }
            yield return current;
        }
    }

    public static string ColumnLetters(int column)
    {
        if (column < 1) throw new ArgumentOutOfRangeException(nameof(column));
        string result = "";
        while (column > 0) { column--; result = (char)('A' + column % 26) + result; column /= 26; }
        return result;
    }

    private static void RequireIdentifier(string value, string context)
    {
        if (string.IsNullOrEmpty(value) || !Identifier.IsMatch(value) || Keywords.Contains(value))
            throw new InvalidOperationException(context + ": C# 식별자로 사용할 수 없습니다: " + value);
        if (value.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 || value.EndsWith(".", StringComparison.Ordinal))
            throw new InvalidOperationException(context + ": 파일 이름으로 사용할 수 없습니다: " + value);
        string stem = value.ToUpperInvariant();
        if (Regex.IsMatch(stem, @"^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$"))
            throw new InvalidOperationException(context + ": 예약된 파일 이름입니다: " + value);
    }

    public static Type ResolveType(string token)
    {
        token = token.Trim();
        if (ScalarTypes.TryGetValue(token, out var scalar)) return scalar;
        if (token.StartsWith("List<", StringComparison.Ordinal) && token.EndsWith(">", StringComparison.Ordinal))
        {
            var element = ResolveType(token.Substring(5, token.Length - 6));
            if (element.IsGenericType) throw new InvalidOperationException("중첩 List는 지원하지 않습니다: " + token);
            return typeof(List<>).MakeGenericType(element);
        }
        var matches = LoadedTypes().Where(t => t.IsEnum && (t.Name == token || t.FullName?.Replace('+', '.') == token)).ToArray();
        if (matches.Length != 1 || !IsPublic(matches[0]) || matches[0].ContainsGenericParameters)
            throw new InvalidOperationException("타입 '" + token + "'을 찾을 수 없거나 모호합니다. 접근 가능한 enum 정의가 필요합니다.");
        // Generated scripts compile into Assembly-CSharp; editor-only enum types cannot be used in players.
        var assembly = matches[0].Assembly.GetName().Name;
        var runtimeAssemblies = UnityEditor.Compilation.CompilationPipeline.GetAssemblies(UnityEditor.Compilation.AssembliesType.Player);
        if (assembly.EndsWith("-Editor", StringComparison.Ordinal) || assembly.StartsWith("UnityEditor", StringComparison.Ordinal) ||
            UnityEditor.Compilation.CompilationPipeline.GetAssemblies().Any(a => a.name == assembly) && !runtimeAssemblies.Any(a => a.name == assembly))
            throw new InvalidOperationException("에디터 전용 enum은 지원하지 않습니다: " + token);
        return matches[0];
    }

    private static bool IsPublic(Type type) => type.IsNested ? type.IsNestedPublic && IsPublic(type.DeclaringType) : type.IsPublic;
    private static IEnumerable<Type> LoadedTypes()
    {
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type[] types;
            try { types = assembly.GetTypes(); }
            catch (ReflectionTypeLoadException e) { types = e.Types; }
            catch (NotSupportedException) { continue; }
            foreach (var type in types) if (type != null) yield return type;
        }
    }

    private static string TypeCode(Type type)
    {
        if (type.IsGenericType) return "global::System.Collections.Generic.List<" + TypeCode(type.GetGenericArguments()[0]) + ">";
        if (type.IsEnum) return "global::" + type.FullName.Replace('+', '.');
        return ScalarTypes.First(pair => pair.Value == type).Key;
    }

    public static ParsedSheet ParseSheet(GoogleSpeadSheetReader.Worksheet worksheet, GstuSpreadSheet data)
    {
        RequireIdentifier(worksheet.title, "worksheet 이름");
        if (string.Equals(worksheet.title, "Editor", StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Editor는 데이터 폴더 이름으로 사용할 수 없습니다.");
        var parsed = new ParsedSheet { worksheet = worksheet };
        var fields = new HashSet<string>(StringComparer.Ordinal);
        int lastColumn = 0;
        foreach (var cell in data.Cells.Values)
        {
            if (cell.Row() == 1 && !string.IsNullOrWhiteSpace(cell.value))
            {
                int index = 0;
                foreach (char c in cell.Column()) index = checked(index * 26 + c - 'A' + 1);
                lastColumn = Math.Max(lastColumn, index);
            }
        }
        if (lastColumn == 0) throw new InvalidOperationException(worksheet.title + "!A1: 헤더가 없습니다.");
        for (int column = 1; column <= lastColumn; column++)
        {
            string address = ColumnLetters(column) + "1";
            string header = CellValue(data, address).Trim();
            try
            {
                string name;
                Type type;
                if (header == "Name") { name = "Name"; type = typeof(string); }
                else
                {
                    var match = Regex.Match(header, @"^([^()]+)\(([^()]+)\)$");
                    if (!match.Success) throw new InvalidOperationException("Name 또는 필드명(타입) 헤더가 필요합니다.");
                    name = match.Groups[1].Value.Trim();
                    type = ResolveType(match.Groups[2].Value);
                }
                RequireIdentifier(name, "필드 이름");
                if (name == parsed.DataTypeName || name == "SchemaSignature" ||
                    typeof(ScriptableObject).GetMember(name, BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static).Length > 0)
                    throw new InvalidOperationException("생성 클래스의 기존 멤버와 충돌하는 필드입니다: " + name);
                if (!fields.Add(name)) throw new InvalidOperationException("중복 필드: " + name);
                parsed.columns.Add(new Column { name = name, type = type, index = column });
            }
            catch (Exception e) { throw CellError(worksheet.title, address, "유효한 헤더 타입", e.Message); }
        }
        if (!parsed.columns.Any(c => c.name == "Name" && c.type == typeof(string)) ||
            !parsed.columns.Any(c => c.name == "Key" && c.type == typeof(int)))
            throw CellError(worksheet.title, "A1", "Name(string), Key(int)", "필수 헤더가 없거나 타입이 다릅니다.");
        var keys = new HashSet<int>();
        var names = new HashSet<string>(StringComparer.Ordinal);
        var groupedRows = data.Cells.Values.Where(c => c.Row() > 1).GroupBy(c => c.Row()).OrderBy(g => g.Key);
        foreach (var group in groupedRows)
        {
            int rowIndex = group.Key;
            var rowCells = group.ToArray();
            if (rowCells.All(c => string.IsNullOrWhiteSpace(c.value))) continue;
            foreach (var cell in rowCells)
            {
                int index = 0;
                foreach (char c in cell.Column()) index = index * 26 + c - 'A' + 1;
                if (index > lastColumn && !string.IsNullOrWhiteSpace(cell.value))
                    throw CellError(worksheet.title, cell.CellRef(), "헤더가 있는 열", "헤더 없는 열에 데이터가 있습니다.");
            }
            var row = new Row();
            foreach (var column in parsed.columns)
            {
                string address = ColumnLetters(column.index) + rowIndex;
                try { row.values.Add(column.name, ParseValue(CellValue(data, address), column.type)); }
                catch (Exception e) { throw CellError(worksheet.title, address, TypeCode(column.type), e.Message); }
            }
            row.key = (int)row.values["Key"];
            row.name = (string)row.values["Name"];
            var nameColumn = parsed.columns.Single(c => c.name == "Name");
            var keyColumn = parsed.columns.Single(c => c.name == "Key");
            if (string.IsNullOrWhiteSpace(row.name))
                throw CellError(worksheet.title, ColumnLetters(nameColumn.index) + rowIndex, "Name(string)", "이름은 필수입니다.");
            if (!names.Add(row.name))
                throw CellError(worksheet.title, ColumnLetters(nameColumn.index) + rowIndex, "고유 Name", "중복 이름: " + row.name);
            if (!keys.Add(row.key))
                throw CellError(worksheet.title, ColumnLetters(keyColumn.index) + rowIndex, "고유 Key(int)", "중복 Key: " + row.key);
            parsed.rows.Add(row);
        }
        parsed.signature = string.Join("|", parsed.columns.Select(c => c.name + ":" + TypeCode(c.type)));
        return parsed;
    }

    private static InvalidOperationException CellError(string sheet, string address, string expected, string reason) =>
        new InvalidOperationException(sheet + "!" + address + " [기대 타입: " + expected + "] " + reason);
    private static string CellValue(GstuSpreadSheet data, string address) => data.Cells.TryGetValue(address, out var cell) ? cell.value ?? "" : "";

    public static object ParseValue(string text, Type type)
    {
        text = text ?? "";
        if (type == typeof(string)) return text;
        string value = text.Trim();
        if (value.Length == 0) throw new FormatException("빈 셀은 이 타입에 허용되지 않습니다.");
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
        {
            Type element = type.GetGenericArguments()[0];
            if (element.IsGenericType || (!element.IsEnum && !ScalarTypes.ContainsValue(element)))
                throw new FormatException("지원하지 않는 List 원소 타입입니다.");
            var list = (IList)Activator.CreateInstance(type);
            foreach (var token in new JsonArrayReader(value).Read())
            {
                bool requireString = element == typeof(string) || element.IsEnum;
                if (token.isString != requireString) throw new FormatException("JSON 원소 타입이 " + TypeCode(element) + "와 다릅니다.");
                if (!requireString && element == typeof(bool) && token.value != "true" && token.value != "false")
                    throw new FormatException("JSON bool에는 true/false가 필요합니다.");
                if (!requireString && element != typeof(bool) && (token.value == "true" || token.value == "false"))
                    throw new FormatException("JSON 숫자 원소가 필요합니다.");
                list.Add(ParseValue(token.value, element));
            }
            return list;
        }
        if (type == typeof(bool) && bool.TryParse(value, out var boolean)) return boolean;
        if (type == typeof(int) && int.TryParse(value, NumberStyles.Integer, Invariant, out var integer)) return integer;
        if (type == typeof(long) && long.TryParse(value, NumberStyles.Integer, Invariant, out var longInteger)) return longInteger;
        if (type == typeof(float) && float.TryParse(value, NumberStyles.Float, Invariant, out var single) && !float.IsNaN(single) && !float.IsInfinity(single)) return single;
        if (type == typeof(double) && double.TryParse(value, NumberStyles.Float, Invariant, out var number) && !double.IsNaN(number) && !double.IsInfinity(number)) return number;
        if (type.IsEnum && Enum.GetNames(type).Contains(value)) return Enum.Parse(type, value, false);
        throw new FormatException("값을 " + TypeCode(type) + "로 변환할 수 없습니다: " + value);
    }

    // A strict JSON array reader keeps integer precision and does not add another JSON package dependency.
    private sealed class JsonArrayReader
    {
        public struct Token { public bool isString; public string value; }
        private readonly string text;
        private int position;
        public JsonArrayReader(string text) { this.text = text; }
        private void White() { while (position < text.Length && " \t\r\n".IndexOf(text[position]) >= 0) position++; }
        private void Expect(char c)
        {
            White();
            if (position >= text.Length || text[position++] != c) throw new FormatException("올바른 JSON 배열이 필요합니다.");
        }
        public List<Token> Read()
        {
            var result = new List<Token>();
            Expect('[');
            White();
            if (position < text.Length && text[position] == ']') { position++; Finish(); return result; }
            while (true)
            {
                White();
                if (position < text.Length && text[position] == '"') result.Add(new Token { isString = true, value = ReadString() });
                else
                {
                    int start = position;
                    while (position < text.Length && text[position] != ',' && text[position] != ']' && " \t\r\n".IndexOf(text[position]) < 0) position++;
                    string raw = text.Substring(start, position - start);
                    if (raw != "true" && raw != "false" && !Regex.IsMatch(raw, @"^-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?$"))
                        throw new FormatException("JSON 배열 원소는 문자열·bool·숫자여야 합니다. null/객체/중첩 배열은 지원하지 않습니다.");
                    result.Add(new Token { value = raw });
                }
                White();
                if (position < text.Length && text[position] == ']') { position++; Finish(); return result; }
                Expect(',');
            }
        }
        private void Finish() { White(); if (position != text.Length) throw new FormatException("JSON 배열 뒤에 불필요한 데이터가 있습니다."); }
        private string ReadString()
        {
            Expect('"');
            var output = new StringBuilder();
            while (position < text.Length)
            {
                char c = text[position++];
                if (c == '"') return output.ToString();
                if (c < 32) throw new FormatException("JSON 문자열의 제어 문자는 이스케이프해야 합니다.");
                if (c != '\\') { output.Append(c); continue; }
                if (position >= text.Length) break;
                c = text[position++];
                switch (c)
                {
                    case '"': case '\\': case '/': output.Append(c); break;
                    case 'b': output.Append('\b'); break;
                    case 'f': output.Append('\f'); break;
                    case 'n': output.Append('\n'); break;
                    case 'r': output.Append('\r'); break;
                    case 't': output.Append('\t'); break;
                    case 'u':
                        if (position + 4 > text.Length || !ushort.TryParse(text.Substring(position, 4), NumberStyles.HexNumber, Invariant, out var code))
                            throw new FormatException("잘못된 JSON Unicode 이스케이프입니다.");
                        output.Append((char)code); position += 4; break;
                    default: throw new FormatException("잘못된 JSON 이스케이프입니다.");
                }
            }
            throw new FormatException("닫히지 않은 JSON 문자열입니다.");
        }
    }

    public static string ValidateAssetFolder(string path)
    {
        if (string.IsNullOrWhiteSpace(path)) throw new InvalidOperationException("출력 경로가 비어 있습니다.");
        string normalized = path.Replace('\\', '/').TrimEnd('/');
        if (normalized != "Assets" && !normalized.StartsWith("Assets/", StringComparison.Ordinal))
            throw new InvalidOperationException("출력 경로는 Assets 내부여야 합니다: " + path);
        if (normalized.Split('/').Any(part => part == "." || part == ".." || part.Length == 0 || part.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0))
            throw new InvalidOperationException("잘못된 출력 경로입니다: " + path);
        string absolute = Path.GetFullPath(normalized);
        string assets = Path.GetFullPath(Application.dataPath);
        if (absolute != assets && !absolute.StartsWith(assets + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("출력 경로가 프로젝트 Assets 밖입니다: " + path);
        // Reject junctions/symlinks so an Assets-looking path cannot write outside the project.
        string current = absolute;
        while (current.Length >= assets.Length)
        {
            if (Directory.Exists(current) && (File.GetAttributes(current) & FileAttributes.ReparsePoint) != 0)
                throw new InvalidOperationException("출력 경로의 링크/정션은 지원하지 않습니다: " + path);
            if (string.Equals(current, assets, StringComparison.OrdinalIgnoreCase)) break;
            current = Path.GetDirectoryName(current);
        }
        return normalized;
    }

    private static void ValidateSettings(GoogleSpeadSheetReader reader)
    {
        foreach (string path in new[] { reader.generatedCodeFolder, reader.dataFolder, reader.catalogFolder })
        {
            string folder = ValidateAssetFolder(path);
            if (folder.Split('/').Any(p => string.Equals(p, "Editor", StringComparison.OrdinalIgnoreCase) || p.EndsWith("~", StringComparison.Ordinal)))
                throw new InvalidOperationException("출력은 런타임에 포함되는 폴더여야 합니다. Editor/~ 폴더는 사용할 수 없습니다: " + path);
        }
    }

    private static void ValidateAssetFile(string path)
    {
        ValidateAssetFolder(Path.GetDirectoryName(path).Replace('\\', '/'));
        if (Directory.Exists(path) || File.Exists(path) && (File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0)
            throw new InvalidOperationException("출력 파일이 폴더이거나 파일 링크입니다: " + path);
        if (File.Exists(path + ".meta") && (File.GetAttributes(path + ".meta") & FileAttributes.ReparsePoint) != 0)
            throw new InvalidOperationException("출력 meta 파일 링크는 지원하지 않습니다: " + path);
    }

    private static void ValidateTypeNames(List<ParsedSheet> sheets)
    {
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var sheet in sheets)
            foreach (string name in new[] { sheet.DataTypeName, sheet.CatalogTypeName })
            {
                RequireIdentifier(name, "생성 타입 이름");
                if (!names.Add(name)) throw new InvalidOperationException("생성 타입/파일 이름 충돌: " + name);
                var conflicts = LoadedTypes().Where(t => t.Name == name && t.FullName != GeneratedNamespace + "." + name).ToArray();
                if (conflicts.Length > 0) throw new InvalidOperationException("기존 타입 이름과 충돌합니다: " + name);
            }
    }

    private static string Literal(string text) => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n") + "\"";
    public static string DataCode(ParsedSheet sheet)
    {
        var code = new StringBuilder(Marker + sheet.DataTypeName + "\nusing UnityEngine;\n\nnamespace " + GeneratedNamespace + "\n{\n");
        code.Append("    public sealed class " + sheet.DataTypeName + " : ScriptableObject\n    {\n");
        code.Append("        public const string SchemaSignature = " + Literal(sheet.signature) + ";\n");
        foreach (var column in sheet.columns)
        {
            code.Append("        public " + TypeCode(column.type) + " " + column.name);
            if (column.type.IsGenericType) code.Append(" = new " + TypeCode(column.type) + "()");
            code.Append(";\n");
        }
        return code.Append("    }\n}\n").ToString();
    }

    public static string CatalogCode(ParsedSheet sheet) => Marker + sheet.CatalogTypeName + "\n" +
        "using System.Collections.Generic;\nusing UnityEngine;\n\nnamespace " + GeneratedNamespace + "\n{\n" +
        "    public sealed class " + sheet.CatalogTypeName + " : ScriptableObject\n    {\n" +
        "        [SerializeField] private List<" + sheet.DataTypeName + "> entries = new List<" + sheet.DataTypeName + ">();\n" +
        "        public IReadOnlyList<" + sheet.DataTypeName + "> Entries => entries;\n" +
        "        public bool TryGetByKey(int key, out " + sheet.DataTypeName + " data)\n        {\n" +
        "            foreach (var entry in entries)\n                if (entry != null && entry.Key == key) { data = entry; return true; }\n" +
        "            data = null;\n            return false;\n        }\n    }\n}\n";

    public static void GenerateCode(GoogleSpeadSheetReader reader, List<ParsedSheet> sheets)
    {
        ValidateSettings(reader);
        ValidateTypeNames(sheets);
        string folder = ValidateAssetFolder(reader.generatedCodeFolder);
        var outputs = new Dictionary<string, string>();
        foreach (var sheet in sheets)
        {
            outputs.Add(folder + "/" + sheet.DataTypeName + ".cs", DataCode(sheet));
            outputs.Add(folder + "/" + sheet.CatalogTypeName + ".cs", CatalogCode(sheet));
        }
        foreach (var output in outputs)
        {
            ValidateAssetFile(output.Key);
            string name = Path.GetFileNameWithoutExtension(output.Key);
            if (File.Exists(output.Key) && !File.ReadAllText(output.Key).StartsWith(Marker + name + "\n", StringComparison.Ordinal))
                throw new InvalidOperationException("도구가 생성하지 않은 코드를 덮어쓸 수 없습니다: " + output.Key);
            var type = FindGeneratedType(name);
            if (type != null && ScriptPath(type) != output.Key)
                throw new InvalidOperationException("다른 경로에 같은 생성 타입이 있습니다. 기존 코드를 수동 이동한 뒤 다시 실행하세요: " + name);
        }
        EnsureFolder(folder);
        // Do not let Unity recompile a half-written pair of Data/Catalog scripts.
        AssetDatabase.StartAssetEditing();
        try
        {
            foreach (var output in outputs)
                if (!File.Exists(output.Key) || File.ReadAllText(output.Key) != output.Value)
                    File.WriteAllText(output.Key, output.Value, new UTF8Encoding(false));
        }
        finally { AssetDatabase.StopAssetEditing(); }
        AssetDatabase.Refresh();
    }

    private static Type FindGeneratedType(string name) => LoadedTypes().SingleOrDefault(t => t.FullName == GeneratedNamespace + "." + name);
    private static string ScriptPath(Type type)
    {
        var instance = ScriptableObject.CreateInstance(type);
        try { return AssetDatabase.GetAssetPath(MonoScript.FromScriptableObject(instance)); }
        finally { UnityEngine.Object.DestroyImmediate(instance); }
    }

    public static void ValidateCompiledSchema(GoogleSpeadSheetReader reader, List<ParsedSheet> sheets)
    {
        if (EditorApplication.isCompiling || EditorUtility.scriptCompilationFailed || EditorApplication.isPlayingOrWillChangePlaymode)
            throw new InvalidOperationException("컴파일 완료 및 오류 해결이 필요합니다.");
        foreach (var sheet in sheets)
        {
            var type = FindGeneratedType(sheet.DataTypeName);
            var catalog = FindGeneratedType(sheet.CatalogTypeName);
            if (type == null || catalog == null)
                throw new InvalidOperationException(sheet.worksheet.title + ": 코드 생성/갱신을 먼저 실행하세요.");
            if (!typeof(ScriptableObject).IsAssignableFrom(type) || !typeof(ScriptableObject).IsAssignableFrom(catalog))
                throw new InvalidOperationException(sheet.worksheet.title + ": 생성 타입이 SO가 아닙니다.");
            string actual = type.GetField("SchemaSignature")?.GetRawConstantValue() as string;
            if (actual != sheet.signature || sheet.columns.Any(c => type.GetField(c.name)?.FieldType != c.type))
                throw new InvalidOperationException(sheet.worksheet.title + ": 헤더 변경 감지.\n기존: " + actual + "\n현재: " + sheet.signature + "\n코드 생성/갱신 후 다시 가져오세요.");
            if (catalog.GetField("entries", BindingFlags.NonPublic | BindingFlags.Instance)?.FieldType != typeof(List<>).MakeGenericType(type))
                throw new InvalidOperationException(sheet.worksheet.title + ": Catalog 코드 생성/갱신이 필요합니다.");
            string folder = ValidateAssetFolder(reader.generatedCodeFolder);
            foreach (var generated in new[] { type, catalog })
                if (ScriptPath(generated) != folder + "/" + generated.Name + ".cs")
                    throw new InvalidOperationException("생성 코드 경로가 일치하지 않습니다: " + generated.Name);
        }
    }

    private sealed class ImportTarget
    {
        public ParsedSheet sheet;
        public Type type;
        public Type catalogType;
        public string folder;
        public string catalogPath;
        public GoogleSpeadSheetReader.ImportRecord previous;
        public Dictionary<int, ScriptableObject> existing = new Dictionary<int, ScriptableObject>();
    }

    public static void ApplyImport(GoogleSpeadSheetReader reader, string sourceId, List<ParsedSheet> sheets)
    {
        ValidateSettings(reader);
        ValidateTypeNames(sheets);
        ValidateCompiledSchema(reader, sheets);
        if (string.IsNullOrWhiteSpace(AssetDatabase.GetAssetPath(reader)))
            throw new InvalidOperationException("Reader SO를 프로젝트에 먼저 저장하세요.");
        var targets = new List<ImportTarget>();
        var paths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var sheet in sheets)
        {
            var target = new ImportTarget
            {
                sheet = sheet, type = FindGeneratedType(sheet.DataTypeName), catalogType = FindGeneratedType(sheet.CatalogTypeName),
                folder = ValidateAssetFolder(reader.dataFolder) + "/" + sheet.worksheet.title,
                catalogPath = ValidateAssetFolder(reader.catalogFolder) + "/" + sheet.CatalogTypeName + ".asset"
            };
            ValidateAssetFolder(target.folder);
            ValidateAssetFile(target.catalogPath);
            if (target.folder == ValidateAssetFolder(reader.catalogFolder))
                throw new InvalidOperationException("행 데이터와 Catalog 폴더가 겹칩니다: " + target.folder);
            target.previous = reader.MutableImports.SingleOrDefault(r => r.sourceId == sourceId && r.sheetId == sheet.worksheet.sheetId &&
                r.dataPath == target.folder && r.catalogPath == target.catalogPath);
            foreach (var other in reader.MutableImports)
                if (other != target.previous && (other.dataPath == target.folder || other.catalogPath == target.catalogPath))
                    throw new InvalidOperationException("다른 소스/시트가 관리하는 출력 경로입니다: " + target.folder);
            if (target.previous != null)
            {
                if (target.previous.catalog == null || target.previous.catalog.GetType() != target.catalogType ||
                    AssetDatabase.GetAssetPath(target.previous.catalog) != target.catalogPath)
                    throw new InvalidOperationException("관리 중인 Catalog가 삭제되거나 이동되었습니다: " + target.catalogPath);
                foreach (var managed in target.previous.rows)
                {
                    string path = AssetDatabase.GUIDToAssetPath(managed.guid);
                    if (!string.IsNullOrEmpty(path)) ValidateAssetFile(path);
                    var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(path);
                    if (asset == null || asset.GetType() != target.type || Path.GetDirectoryName(path).Replace('\\', '/') != target.folder ||
                        (int)target.type.GetField("Key").GetValue(asset) != managed.key || target.existing.ContainsKey(managed.key))
                        throw new InvalidOperationException("관리 중인 행 SO의 Key/타입/위치가 변경되었습니다: " + managed.key);
                    target.existing.Add(managed.key, asset);
                }
            }
            else if (File.Exists(target.catalogPath) || AssetDatabase.LoadMainAssetAtPath(target.catalogPath) != null)
                throw new InvalidOperationException("관리하지 않는 Catalog를 덮어쓸 수 없습니다: " + target.catalogPath);
            if (!paths.Add(target.catalogPath)) throw new InvalidOperationException("Catalog 출력 경로 충돌: " + target.catalogPath);
            foreach (var row in sheet.rows)
            {
                string path = target.existing.TryGetValue(row.key, out var asset) ? AssetDatabase.GetAssetPath(asset) : target.folder + "/" + row.key.ToString(Invariant) + ".asset";
                ValidateAssetFile(path);
                if (!paths.Add(path)) throw new InvalidOperationException("행 SO 출력 경로 충돌: " + path);
                if (asset == null && (File.Exists(path) || AssetDatabase.LoadMainAssetAtPath(path) != null))
                    throw new InvalidOperationException("관리하지 않는 행 SO를 덮어쓸 수 없습니다: " + path);
            }
            targets.Add(target);
        }

        // Keep exact asset/meta bytes for rollback on disk/save failures, including deleted rows.
        var backups = new Dictionary<string, byte[]>();
        string readerPath = AssetDatabase.GetAssetPath(reader);
        Backup(backups, readerPath);
        foreach (var target in targets)
        {
            Backup(backups, target.catalogPath);
            foreach (var row in target.sheet.rows)
                Backup(backups, target.existing.TryGetValue(row.key, out var asset) ? AssetDatabase.GetAssetPath(asset) : target.folder + "/" + row.key.ToString(Invariant) + ".asset");
            foreach (var asset in target.existing.Values) Backup(backups, AssetDatabase.GetAssetPath(asset));
        }
        string readerBefore = EditorJsonUtility.ToJson(reader);
        try
        {
            foreach (var target in targets)
            {
                EnsureFolder(target.folder);
                EnsureFolder(ValidateAssetFolder(reader.catalogFolder));
                var record = new GoogleSpeadSheetReader.ImportRecord
                { sourceId = sourceId, sheetId = target.sheet.worksheet.sheetId, dataPath = target.folder, catalogPath = target.catalogPath };
                var entries = (IList)Activator.CreateInstance(typeof(List<>).MakeGenericType(target.type));
                foreach (var row in target.sheet.rows)
                {
                    bool exists = target.existing.TryGetValue(row.key, out var asset);
                    if (!exists) asset = ScriptableObject.CreateInstance(target.type);
                    foreach (var column in target.sheet.columns) target.type.GetField(column.name).SetValue(asset, row.values[column.name]);
                    asset.name = row.name;
                    string path = exists ? AssetDatabase.GetAssetPath(asset) : target.folder + "/" + row.key.ToString(Invariant) + ".asset";
                    if (!exists) AssetDatabase.CreateAsset(asset, path);
                    SaveChecked(asset, path);
                    entries.Add(asset);
                    record.rows.Add(new GoogleSpeadSheetReader.ManagedRow { key = row.key, guid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(asset)) });
                }
                record.catalog = target.previous?.catalog;
                if (record.catalog == null)
                {
                    record.catalog = ScriptableObject.CreateInstance(target.catalogType);
                    AssetDatabase.CreateAsset(record.catalog, target.catalogPath);
                }
                target.catalogType.GetField("entries", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(record.catalog, entries);
                SaveChecked(record.catalog, target.catalogPath);
                if (target.previous != null) reader.MutableImports.Remove(target.previous);
                reader.MutableImports.Add(record);
            }
            // Delete only previously recorded rows, and only after all new catalogs have been saved.
            foreach (var target in targets)
            {
                var active = new HashSet<int>(target.sheet.rows.Select(r => r.key));
                foreach (var pair in target.existing)
                    if (!active.Contains(pair.Key) && !AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(pair.Value)))
                        throw new IOException("삭제 실패: " + target.sheet.worksheet.title + " Key=" + pair.Key);
            }
            SaveChecked(reader, readerPath);
        }
        catch
        {
            foreach (var pair in backups)
            {
                if (pair.Value == null) { if (File.Exists(pair.Key)) File.Delete(pair.Key); }
                else File.WriteAllBytes(pair.Key, pair.Value);
            }
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
            foreach (var path in backups.Keys.Where(p => p.EndsWith(".asset", StringComparison.Ordinal)))
                if (File.Exists(path)) AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
            EditorJsonUtility.FromJsonOverwrite(readerBefore, reader);
            EditorUtility.SetDirty(reader);
            AssetDatabase.SaveAssetIfDirty(reader);
            throw;
        }
    }

    private static void Backup(Dictionary<string, byte[]> backups, string assetPath)
    {
        foreach (string path in new[] { assetPath, assetPath + ".meta" })
            if (!backups.ContainsKey(path)) backups.Add(path, File.Exists(path) ? File.ReadAllBytes(path) : null);
    }

    private static void SaveChecked(ScriptableObject asset, string expectedPath)
    {
        if (AssetDatabase.GetAssetPath(asset) != expectedPath || string.IsNullOrEmpty(AssetDatabase.AssetPathToGUID(expectedPath)))
            throw new IOException("자산 생성에 실패했습니다: " + expectedPath);
        EditorUtility.SetDirty(asset);
        AssetDatabase.SaveAssetIfDirty(asset);
        if (!File.Exists(expectedPath) || EditorUtility.IsDirty(asset))
            throw new IOException("자산 저장에 실패했습니다: " + expectedPath);
    }

    private static void EnsureFolder(string folder)
    {
        ValidateAssetFolder(folder);
        string current = "Assets";
        foreach (string part in folder.Split('/').Skip(1))
        {
            string next = current + "/" + part;
            if (!AssetDatabase.IsValidFolder(next) && string.IsNullOrEmpty(AssetDatabase.CreateFolder(current, part)))
                throw new IOException("폴더 생성 실패: " + next);
            current = next;
        }
    }
}

[CustomEditor(typeof(GoogleSpeadSheetReader))]
public sealed class GoogleSpeadSheetReaderEditor : Editor
{
    public override VisualElement CreateInspectorGUI()
    {
        var reader = (GoogleSpeadSheetReader)target;
        var root = new VisualElement();
        var settings = new VisualElement();
        foreach (string name in new[] { "spreadsheetId", "accessMode", "generatedCodeFolder", "dataFolder", "catalogFolder", "requestTimeoutSeconds" })
            settings.Add(new PropertyField(serializedObject.FindProperty(name)));
        root.Add(settings);
        var actions = new VisualElement();
        foreach (GoogleSpeadSheetReaderPipeline.Operation operation in Enum.GetValues(typeof(GoogleSpeadSheetReaderPipeline.Operation)))
        {
            string label = operation == GoogleSpeadSheetReaderPipeline.Operation.Discover ? "시트 검색" :
                operation == GoogleSpeadSheetReaderPipeline.Operation.Validate ? "전체 검증" :
                operation == GoogleSpeadSheetReaderPipeline.Operation.Generate ? "코드 생성 / 갱신" : "전체 데이터 가져오기";
            actions.Add(new Button(() => { serializedObject.ApplyModifiedProperties(); GoogleSpeadSheetReaderPipeline.Start(reader, operation); }) { text = label });
        }
        root.Add(actions);
        var status = new HelpBox("", HelpBoxMessageType.Info);
        var error = new HelpBox("", HelpBoxMessageType.Error);
        var sheetList = new Foldout { text = "Worksheet / 생성 타입", value = true };
        var catalogs = new Foldout { text = "Catalog 참조", value = true };
        root.Add(status); root.Add(error); root.Add(sheetList); root.Add(catalogs);
        string snapshot = null;
        root.schedule.Execute(() =>
        {
            if (reader == null) return;
            settings.SetEnabled(!reader.IsBusy);
            actions.SetEnabled(!reader.IsBusy && !EditorApplication.isCompiling && !EditorApplication.isPlayingOrWillChangePlaymode && !EditorUtility.scriptCompilationFailed);
            status.text = reader.Status ?? "준비";
            error.text = reader.LastError ?? "";
            error.style.display = string.IsNullOrEmpty(reader.LastError) ? DisplayStyle.None : DisplayStyle.Flex;
            string current = string.Join("|", reader.Worksheets.Select(s => s.title + ":" + s.sheetId)) + "/" +
                string.Join("|", reader.Imports.Select(i => i.catalogPath + ":" + (i.catalog == null ? "null" : i.catalog.GetInstanceID().ToString())));
            if (snapshot == current) return;
            snapshot = current;
            sheetList.Clear();
            foreach (var sheet in reader.Worksheets)
                sheetList.Add(new Label(sheet.title + " (" + sheet.rowCount + "행 × " + sheet.columnCount + "열) → " + sheet.title + "Data / " + sheet.title + "Catalog"));
            catalogs.Clear();
            foreach (var import in reader.Imports)
            {
                var field = new ObjectField(import.catalogPath) { objectType = typeof(ScriptableObject), value = import.catalog, allowSceneObjects = false };
                field.SetEnabled(false);
                catalogs.Add(field);
            }
        }).Every(200);
        return root;
    }
}
#endif
